#!/bin/bash

git status > /dev/null
[ $? -ne 0 ] && echo "Not in a git repository" 1>&2 && exit 1

[ -z $1 ] && exit 1

git config --add svn-remote.$1.url svn+ssh://username@svn.repo.host/path/to/branches/$1
git config --add svn-remote.$1.fetch :refs/remotes/$1
git svn fetch $1
git checkout -b local-$1 -t $1
git svn rebase $1
